# Generated by Django 3.1.1 on 2020-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.JSONField()),
                ('data_style', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='modal',
            name='information',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='ModalSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.CharField(blank=True, max_length=250)),
                ('modal_data', models.ManyToManyField(blank=True, to='modal.ModalData')),
            ],
        ),
        migrations.AddField(
            model_name='modal',
            name='modal_section',
            field=models.ManyToManyField(blank=True, to='modal.ModalSection'),
        ),
    ]
