# Generated by Django 3.1.1 on 2020-09-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0012_auto_20200925_1805'),
        ('modal', '0002_auto_20200927_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modal',
        ),
    ]
