# Generated by Django 3.1.1 on 2020-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0003_delete_modal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modaldata',
            name='data',
            field=models.CharField(max_length=500),
        ),
    ]
