# Generated by Django 3.1.1 on 2020-09-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0004_auto_20200927_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='modaldata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
