# Generated by Django 3.1.1 on 2020-10-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0005_modaldata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalsection',
            name='collapse',
            field=models.BooleanField(default=False),
        ),
    ]
