# Generated by Django 3.1.1 on 2020-09-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20200923_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ManyToManyField(blank=True, to='subject.Section'),
        ),
    ]
