# Generated by Django 3.1.1 on 2020-09-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20200923_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='DropDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('item', models.ManyToManyField(blank=True, to='subject.Item')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='dropdown',
            field=models.ManyToManyField(blank=True, to='subject.DropDown'),
        ),
    ]
