# Generated by Django 3.1.1 on 2020-09-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_auto_20200923_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='information',
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='website',
            field=models.BooleanField(default=False),
        ),
    ]
