# Generated by Django 3.1.1 on 2020-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_auto_20200924_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='website',
            field=models.CharField(max_length=200),
        ),
    ]
