# Generated by Django 3.1.1 on 2020-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0009_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdown',
            name='icon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
