# Generated by Django 3.1.1 on 2020-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0010_dropdown_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='model',
            new_name='modal_boolean',
        ),
        migrations.AddField(
            model_name='item',
            name='modal',
            field=models.ManyToManyField(blank=True, to='subject.Modal'),
        ),
    ]
