# Generated by Django 3.1.1 on 2020-09-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0001_initial'),
        ('subject', '0011_auto_20200925_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modal',
        ),
        migrations.AlterField(
            model_name='item',
            name='modal',
            field=models.ManyToManyField(blank=True, to='modal.Modal'),
        ),
    ]
