# Generated by Django 3.1.1 on 2020-09-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modal', '0003_delete_modal'),
        ('subject', '0012_auto_20200925_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modal',
            field=models.ManyToManyField(blank=True, to='modal.ModalSection'),
        ),
    ]
